-- MySQL Script generated by MySQL Workbench
-- Sat Feb 24 16:43:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horarios` DEFAULT CHARACTER SET utf8 ;
USE `horarios` ;

-- -----------------------------------------------------
-- Table `horarios`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`periodos` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `nombre_periodo` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`horarios` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`docentes` (
  `id_docente` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `horas_disponibles` INT(5) NOT NULL,
  `tipo_contrato` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `nivel_educacion` VARCHAR(100) NOT NULL,
  `especializacion` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `cedula` VARCHAR(20) NOT NULL,
  `estado` INT(5) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_docente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`aulas` (
  `id_aula` VARCHAR(30) NOT NULL,
  `capacidad` INT NOT NULL,
  `bloque` VARCHAR(10) NOT NULL,
  `observacion` VARCHAR(300) NULL,
  PRIMARY KEY (`id_aula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`materias` (
  `cod_materia` VARCHAR(20) NOT NULL,
  `nombre_materia` VARCHAR(100) NOT NULL,
  `departamento` VARCHAR(45) NOT NULL,
  `horas_semana` INT(5) NOT NULL,
  PRIMARY KEY (`cod_materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`cursos` (
  `nrc` INT NOT NULL AUTO_INCREMENT,
  `id_docente` VARCHAR(45) NOT NULL,
  `cod_materia` VARCHAR(20) NOT NULL,
  `id_aula` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`nrc`, `id_docente`, `cod_materia`, `id_aula`),
  CONSTRAINT `fk_cursos_docentes1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `horarios`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_materias1`
    FOREIGN KEY (`cod_materia`)
    REFERENCES `horarios`.`materias` (`cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cursos_aulas1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `horarios`.`aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`carreras` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre_carrera` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`usuarios` (
  `id_usuario` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`perfiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`perfiles` (
  `id_perfil` INT NOT NULL AUTO_INCREMENT,
  `tipo_perfil` VARCHAR(45) NOT NULL,
  `privilegios` VARCHAR(300) NOT NULL,
  `id_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_perfil`, `id_usuario`),
  CONSTRAINT `fk_perfiles_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `horarios`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`periodos_horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`periodos_horarios` (
  `id_periodo_horario` INT NOT NULL AUTO_INCREMENT,
  `id_periodo` INT NOT NULL,
  `id_horario` INT NOT NULL,
  PRIMARY KEY (`id_periodo_horario`, `id_periodo`, `id_horario`),
  CONSTRAINT `fk_periodos_has_horarios_periodos`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `horarios`.`periodos` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodos_has_horarios_horarios1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `horarios`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`horarios_aulas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`horarios_aulas` (
  `id_horario__aula` INT NOT NULL AUTO_INCREMENT,
  `id_horario` INT NOT NULL,
  `id_aula` VARCHAR(30) NOT NULL,
  `disponible` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_horario__aula`, `id_horario`, `id_aula`),
  CONSTRAINT `fk_horarios_has_aulas_horarios1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `horarios`.`horarios` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horarios_has_aulas_aulas1`
    FOREIGN KEY (`id_aula`)
    REFERENCES `horarios`.`aulas` (`id_aula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`periodos_docentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`periodos_docentes` (
  `id_periodo_docente` INT NOT NULL AUTO_INCREMENT,
  `id_periodo` INT NOT NULL,
  `id_docente` VARCHAR(45) NOT NULL,
  `horas_asignadas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_periodo_docente`, `id_periodo`, `id_docente`),
  CONSTRAINT `fk_periodos_has_docentes_periodos1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `horarios`.`periodos` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodos_has_docentes_docentes1`
    FOREIGN KEY (`id_docente`)
    REFERENCES `horarios`.`docentes` (`id_docente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`carreras_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horarios`.`carreras_materias` (
  `id_carrera_materia` INT NOT NULL AUTO_INCREMENT,
  `id_carrera` INT NOT NULL,
  `cod_materia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_carrera_materia`, `id_carrera`, `cod_materia`),
  CONSTRAINT `fk_carreras_has_materias_carreras1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `horarios`.`carreras` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carreras_has_materias_materias1`
    FOREIGN KEY (`cod_materia`)
    REFERENCES `horarios`.`materias` (`cod_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
